[project]
name = "mypackage"
version = "0.1.1"
description = "My package."
license = "MIT"
readme = "README.rst"
requires-python = ">=3.9,<4.0"
dependencies = [
    "attrs>=25.3.0,<26.0.0",
]

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
